config/routes.rb
Barmanager::Application.routes.draw do
  root :to => 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  match 'sells/process_sells' => "sells#process_sells"
  match 'update_location' => "welcome#update_location"
  resources :bars do
    resources :expansions do
      member do
        get 'add_to_bar'
      end
    end
    
    resources :features do
      member do
        get 'add_to_bar'
      end
    end
    
    resources :enlargements do
      member do
        get 'add_to_bar'
      end
    end
  end

  resources :sells
  resources :bank_transactions

  namespace :api do
    resources :bars do
      resources :expansions do
        member do
          get 'add_to_bar'
        end
      end
      
      resources :features do
        member do
          get 'add_to_bar'
        end
      end
      
      resources :enlargements do
        member do
          get 'add_to_bar'
        end
      end
    end

    resources :cities
    resources :bank_transactions
    resources :users do
      collection do
        post 'request_token'
      end
    end
  end

end

app/models/enlargement.rb
class Enlargement < ActiveRecord::Base
  attr_accessible :capacity, :description, :investment, :name, :icon

  has_many :bar_enlargements
  has_many :bars, :through => :bar_enlargements
end

app/controllers/api/enlargements_controller.rb
class Api::EnlargementsController < Api::ApiController

  def index
    bar = current_user.bars.where(:id => params[:bar_id]).first

    respond_to do |format|
      if bar.current_enlargements.empty? and bar.available_enlargements.empty?
        format.json { render json: { "error" => "Er is een fout opgetreden bij het ophalen van de bar enlargements." }, :status => 422 }
      else
        format.json { render json: bar.to_json(:include => [:current_enlargements, :available_enlargements]) }
      end
    end
  end

  def add_to_bar
    bar = current_user.bars.where(:id => params[:bar_id]).first
    enlargement = Enlargement.find(params[:id])

    if bar.nil? or enlargement.nil?
      error = true
    else
      bar_enlargement = BarEnlargement.new
      bar_enlargement.bar = bar
      bar_enlargement.enlargement = enlargement
      
      if bar_enlargement.save
        error = false
      else
        error = true
      end
    end

    respond_to do |format|
      if error == true
        format.json { render json: { "error" => "Bar enlargement niet aangemaakt." }, :status => 422 }
      else
        format.json { render json: bar.to_json(:include => [:current_enlargements, :available_enlargements]) }
      end
    end
  end
end

app/controllers/enlargements_controller.rb
class EnlargementsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_location

  def index
    @bar = Bar.find(params[:bar_id])
    @enlargements = Enlargement.all
  end

  def add_to_bar
    @bar = Bar.find(params[:bar_id])
    @enlargement = Enlargement.find(params[:id])

    bar_enlargement = BarEnlargement.new
    bar_enlargement.bar = @bar
    bar_enlargement.enlargement = @enlargement
    
    bar_enlargement.save

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/enlargements_helper.rb
module EnlargementsHelper
end

app/views/enlargements/_enlargement_status.html.haml
- if bar.enlargements.include?(enlargement)
  In bezit
- else
  =link_to "Aanschaffen", add_to_bar_bar_enlargement_path(bar, enlargement), :class => "btn btn-success", :remote => true

app/views/enlargements/add_to_bar.js.erb
$('table.enlargements tr[data-enlargement-id=<%=@enlargement.id%>] td.status').html('<%=escape_javascript(render :partial => "enlargement_status", :locals => {:bar => @bar, :enlargement => @enlargement})%>');

app/views/enlargements/index.html.haml
%h1 Bar Uitbreidingen!

%table.table.table-striped.enlargements
  %thead
    %tr
      %th Naam
      %th Omschrijving
      %th Investering
      %th Capaciteit
  %tbody
    - @enlargements.each do |enlargement|
      %tr{:"data-enlargement-id" => enlargement.id}
        %td=enlargement.name
        %td=enlargement.description
        %td=number_to_currency enlargement.investment
        %td="+ #{enlargement.capacity} personen"
        %td.status=render :partial => "enlargement_status", :locals => {:bar => @bar, :enlargement => enlargement}