config/routes.rb
Barmanager::Application.routes.draw do
  root :to => 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  match 'sells/process_sells' => "sells#process_sells"
  match 'update_location' => "welcome#update_location"
  resources :bars do
    resources :expansions do
      member do
        get 'add_to_bar'
      end
    end
    
    resources :features do
      member do
        get 'add_to_bar'
      end
    end
    
    resources :enlargements do
      member do
        get 'add_to_bar'
      end
    end
  end

  resources :sells
  resources :bank_transactions

  namespace :api do
    resources :bars do
      resources :expansions do
        member do
          get 'add_to_bar'
        end
      end
      
      resources :features do
        member do
          get 'add_to_bar'
        end
      end
      
      resources :enlargements do
        member do
          get 'add_to_bar'
        end
      end
    end

    resources :cities
    resources :bank_transactions
    resources :users do
      collection do
        post 'request_token'
      end
    end
  end

end

app/models/expansion.rb
class Expansion < ActiveRecord::Base
  attr_accessible :description, :investment, :max_use, :name, :popularity, :profit, :revenue, :icon

  has_many :bar_expansions
  has_many :bars, :through => :bar_expansions
end

app/controllers/api/expansions_controller.rb
class Api::ExpansionsController < Api::ApiController

  def index
    bar = current_user.bars.where(:id => params[:bar_id]).first

    respond_to do |format|
      if bar.current_expansions.empty? and bar.available_expansions.empty?
        format.json { render json: { "error" => "Er is een fout opgetreden bij het ophalen van de bar expansions." }, :status => 422 }
      else
        format.json { render json: bar.to_json(:include => [:current_expansions, :available_expansions]) }
      end
    end
  end

  def add_to_bar
    bar = current_user.bars.where(:id => params[:bar_id]).first
    expansion = Expansion.find(params[:id])

    if bar.nil? or expansion.nil?
      error = true
    else
      bar_expansion = BarExpansion.new
      bar_expansion.bar = bar
      bar_expansion.expansion = expansion
      
      if bar_expansion.save
        error = false
      else
        error = true
      end
    end

    respond_to do |format|
      if error == true
        format.json { render json: { "error" => "Bar expansion niet aangemaakt." }, :status => 422 }
      else
        format.json { render json: bar.to_json(:include => [:current_expansions, :available_expansions]) }
      end
    end
  end
end

app/controllers/expansions_controller.rb
class ExpansionsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_location
  
  def index
    @bar = Bar.find(params[:bar_id])
    @expansions = Expansion.all
  end

  def add_to_bar
    @bar = Bar.find(params[:bar_id])
    @expansion = Expansion.find(params[:id])

    bar_expansion = BarExpansion.new
    bar_expansion.bar = @bar
    bar_expansion.expansion = @expansion
    
    bar_expansion.save

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/expansions_helper.rb
module ExpansionsHelper
end

app/views/expansions/_expansion_status.html.haml
- if bar.expansions.include?(expansion)
  In bezit
- else
  =link_to "Aanschaffen", add_to_bar_bar_expansion_path(bar, expansion), :class => "btn btn-success", :remote => true

app/views/expansions/add_to_bar.js.erb
$('table.expansions tr[data-expansion-id=<%=@expansion.id%>] td.status').html('<%=escape_javascript(render :partial => "expansion_status", :locals => {:bar => @bar, :expansion => @expansion})%>');

app/views/expansions/index.html.haml
%h1 Bar uitbreidingen

%table.table.table-striped.expansions
  %thead
    %tr
      %th Naam
      %th Omschrijving
      %th Investering
      %th Omzet
      %th Winstmarge
      %th Populariteit
      %th Duurzaamheid
  %tbody
    - @expansions.each do |expansion|
      %tr{:"data-expansion-id" => expansion.id}
        %td=expansion.name
        %td=expansion.description
        %td=number_to_currency expansion.investment
        %td=number_to_currency expansion.revenue
        %td="#{expansion.profit}%"
        %td=expansion.popularity
        %td
          - if !expansion.max_use.nil? and expansion.max_use > 0
            ="Uitbreiding kan #{expansion.max_use} keer gebruikt worden."
          - else
            ="Onbeperkt"
        %td.status=render :partial => "expansion_status", :locals => {:bar => @bar, :expansion => expansion}