config/routes.rb
Barmanager::Application.routes.draw do
  root :to => 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  match 'sells/process_sells' => "sells#process_sells"
  match 'update_location' => "welcome#update_location"
  resources :bars do
    resources :expansions do
      member do
        get 'add_to_bar'
      end
    end
    
    resources :features do
      member do
        get 'add_to_bar'
      end
    end
    
    resources :enlargements do
      member do
        get 'add_to_bar'
      end
    end
  end

  resources :sells
  resources :bank_transactions

  namespace :api do
    resources :bars do
      resources :expansions do
        member do
          get 'add_to_bar'
        end
      end
      
      resources :features do
        member do
          get 'add_to_bar'
        end
      end
      
      resources :enlargements do
        member do
          get 'add_to_bar'
        end
      end
    end

    resources :cities
    resources :bank_transactions
    resources :users do
      collection do
        post 'request_token'
      end
    end
  end

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  attr_accessible :name, :capacity
  attr_accessor :current_user
  
  belongs_to :user
  belongs_to :city

  has_many :bar_expansions
  has_many :bar_features
  has_many :bar_enlargements
  has_many :expansions, :through => :bar_expansions
  has_many :features, :through => :bar_features
  has_many :enlargements, :through => :bar_enlargements
  has_many :sells, :through => :bar_expansions
  has_many :bank_transactions

  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates :name, :presence => true
  validates :city_id, :presence => true, :uniqueness => {:scope => :user_id}
  
  validates_associated :user
  validates_associated :city
  
  before_validation :find_or_create_city

  def current_expansions
    expansions
  end

  def available_expansions
    Expansion.all - expansions
  end

  def current_features
    features
  end

  def available_features
    Feature.all - features
  end

  def current_enlargements
    enlargements
  end

  def available_enlargements
    Enlargement.all - enlargements
  end

  def is_owned_by_user?(user=nil)
    user ||= current_user
    return self.user == user
  end

  def find_or_create_city(lat=nil, lng=nil)
    lat ||= self.latitude
    lng ||= self.longitude

    bar_city = Geocoder.search("#{lat},#{lng}")[0]
    city = City.find_by_name(bar_city.city)
    if city
      self.city = city
    else
      self.city = City.create!(:name => bar_city.city, :country => bar_city.country_code)
    end
  end

  def popularity
    total = self.expansions.sum(&:popularity)
    self.bar_features.each do |bar_feature|
      if bar_feature.active
        total += bar_feature.feature.popularity
      end
    end
    total
  end

  def potential_visitors
    (self.city.population * 0.02).round(0) * (self.city_popularity / 100)
  end

  def daily_visitors
    if potential_visitors < self.capacity
      potential_visitors
    else
      self.capacity
    end
  end

  def city_popularity
    total_popularity = self.city.bars.sum(&:popularity).to_f

    if self.popularity == 0 or total_popularity == 0
      return 0
    else
      return ( self.popularity.to_f / total_popularity * 100 )
    end
  end

  def capacity
    read_attribute(:capacity) + self.enlargements.sum(&:capacity)
  end

  def revenue_growth
    if self.bank_transactions.count > 1
      self.bank_transactions.where("created_at BETWEEN ? and ?", Time.now - 1.day, Time.now).sum(&:amount)
    elsif self.bank_transactions.count == 1
      100
    else
      0
    end
  end
end

app/controllers/api/bars_controller.rb
class Api::BarsController < Api::ApiController

  def index
    bars = current_user.bars

    respond_to do |format|
      format.json { render json: bars.to_json(:include => :city, :methods => :popularity) }
      format.xml { render xml: bars.to_xml(:include => :city) }
    end
  end

  def show
    bar = current_user.bars.where(:id => params[:id]).first

    respond_to do |format|
      if bar.nil?
        format.json { render json: { "error" => "Bar niet gevonden." }, :status => 422 }
      else
        format.json { render json: bar.to_json(:include => :city) }
      end
    end
  end

  def create
    bar = Bar.new()
    bar.name = params[:name]
    bar.user = current_user 
    bar.latitude = params[:latitude]
    bar.longitude = params[:longitude]

    respond_to do |format|
      if bar.save
        format.json { render json: bar, status: :created }
      else
        format.json { render json: { "error" => "Bar kon niet worden toegevoegd." }, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @bars = current_user.bars.all

    respond_to do |format|
      format.html
      format.json { render json: @bars }
    end
  end

  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bar }
    end
  end

  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bar }
      format.js
    end
  end

  def create
    @bar = Bar.new(params[:bar])
    @bar.user = current_user 
    @bar.latitude = session[:location][:latitude]
    @bar.longitude = session[:location][:longitude]

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
        format.js
      else
        format.html {
          flash[:error] = "Er is een fout opgetreden, je hebt op je huidige locatie al een bar geopend."
          render action: "new"
        }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/views/bars/_city_info.html.haml
.city_info
  %h1
    =@location[0].city
    .btn.refresh_location
      %i.icon-refresh
  .well
    .city_info_box
      .city_info_title
        Inwoners
      .city_info_icon
        %i.icon-group
      .city_info_number
        123.000
    .city_info_box
      .city_info_title
        Omzet
      .city_info_icon
        %i.icon-money
      .city_info_number
        =number_to_currency(5000000)
    .city_info_box.last
      .city_info_title
        Aantal Bars
      .city_info_icon
        %i.icon-info-sign
      .city_info_number
        4/5
    .clearfix

app/views/bars/_dashboard_bar_info.html.haml
.dashboard_bar{:class => ( (index+1)%3 == 0 ? 'last' : '')}
  .bar_ribbon
    .bar_name=bar.name
  .bar_stats
    %table.table.table-striped
      %tbody
        %tr
          %td
            %i.icon-map-marker
            Locatie
          %td=bar.city.name
        %tr
          %td
            %i.icon-heart
            Populariteit
          %td="#{bar.city_popularity.round(0)}%"
        %tr
          %td
            %i.icon-money
            Laatste omzet
          %td= number_to_currency bar.revenue_growth
  .bar_expansions
    - bar.expansions.each do |expansion|
      %div
        %i.icon-glass
        = expansion.name
  .bar_features
    - bar.features.each do |feature|
      %div
        %i.icon-star
        = feature.name
  .bar_enlargements
    - bar.enlargements.each do |enlargement|
      %div
        %i.icon-wrench
        = enlargement.name

  .bar_link  
    = link_to bar_path(bar) do
      .btn.btn-large Bar bezoeken

app/views/bars/_form.html.haml
= form_for @bar do |f|
  - if @bar.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bar.errors.count, "error")} prohibited this bar from being saved:"
      %ul
        - @bar.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/bars/new.html.haml
.new_bar.row
  .span8
    .content
      .new_bar_title Start nu je eigen bar!
      .lead Al meer dan 3,5 miljoen mensen gingen je voor!
      .location_info
  .span4
    .content
      .new_bar_title Naam van je bar!
      = form_for @bar do |f|
        %div.control-group{:class => ( @bar.errors.any? ? "error" : "") }
          = f.text_field :name, :placeholder => "The Royal Bar"

        = f.submit "Maak je bar aan!", :class => 'btn'

app/views/bars/show.html.haml
%h1="Bar #{@bar.name}"
%table.table
  %thead
    %tr
      %th Locatie
      %th Populariteit
      %th Stad percentage populariteit
      %th Capaciteit
      %th Dagelijkse bezoekers
  %tbody
    %tr
      %td=@bar.city.name
      %td=@bar.popularity
      %td=@bar.city_popularity
      %td=@bar.capacity
      %td="#{@bar.daily_visitors} potentieel: #{@bar.potential_visitors.round(0)}"
%hr
%h2 Features:
%table.table
  %thead
    %tr
      %th Feature
      %th Actief
  %tbody
    - @bar.bar_features.each do |bar_feature|
      %tr
        %td=bar_feature.feature.name
        %td
          - if bar_feature.active
            Ja
          - else 
            Nee
.lead
  = link_to "Features toevoegen?", bar_features_path(@bar), :class => "btn btn-success"

%h2 Expansions:
%table.table
  %thead
    %tr
      %th Expansion
  %tbody
    - @bar.expansions.each do |expansion|
      %tr
        %td=expansion.name
.lead
  = link_to "Expansions toevoegen?", bar_expansions_path(@bar), :class => "btn btn-success"

%h2 Uitbreideingen:
%table.table
  %thead
    %tr
      %th Uitbreiding
  %tbody
    - @bar.enlargements.each do |enlargement|
      %tr
        %td=enlargement.name
.lead
  = link_to "Uitbreiding toevoegen?", bar_enlargements_path(@bar), :class => "btn btn-success"