config/routes.rb
Barmanager::Application.routes.draw do
  root :to => 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => 'login', :sign_out => 'logout'}

  match 'sells/process_sells' => "sells#process_sells"
  match 'update_location' => "welcome#update_location"
  resources :bars do
    resources :expansions do
      member do
        get 'add_to_bar'
      end
    end
    
    resources :features do
      member do
        get 'add_to_bar'
      end
    end
    
    resources :enlargements do
      member do
        get 'add_to_bar'
      end
    end
  end

  resources :sells
  resources :bank_transactions

  namespace :api do
    resources :bars do
      resources :expansions do
        member do
          get 'add_to_bar'
        end
      end
      
      resources :features do
        member do
          get 'add_to_bar'
        end
      end
      
      resources :enlargements do
        member do
          get 'add_to_bar'
        end
      end
    end

    resources :cities
    resources :bank_transactions
    resources :users do
      collection do
        post 'request_token'
      end
    end
  end

end

app/views/layouts/_current_location.html.haml
- if session[:location]
  .lead="Huidige locatie: #{session[:location][:city].name}"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Barmanager"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    <link href='http://fonts.googleapis.com/css?family=Cinzel+Decorative' rel='stylesheet' type='text/css'>
    = stylesheet_link_tag "application", :media => "all"
    / %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    / %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    / %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    / %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    / %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %ul.nav
            %li=link_to "Home", root_url
            - if current_user
              %li=link_to "Verkopen", sells_path
              - current_user.bars.each do |bar|
                %li=link_to bar.name, bar_path(bar)

          .pull-right
            - unless current_user
              = link_to user_omniauth_authorize_path(:facebook), :class => "btn btn-info", :"data-no-turbolink" => "true" do
                %i.icon-facebook
                Inloggen met Facebook
            - else
              ="Welkom #{current_user.name}, je huidige balans is:"
              = link_to bank_transactions_path, :class => "btn btn-success" do
                %i.icon-money
                =number_to_currency(current_user.balance)
              = link_to destroy_user_session_path, :method => :delete, :class => "btn btn-danger" do
                %i.icon-signout
                Sign out

    .container
      .current_location
        =render "layouts/current_location"
      .content
        = bootstrap_flash
        = yield
    = javascript_include_tag "application"